apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: login-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: login-app
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
