name: Deploy Login App to GKE

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: your-gcp-project-id
  GKE_CLUSTER: your-gke-cluster
  GKE_REGION: asia-south1
  GAR_ZONE: asia-south1
  GAR_REPO: login-app-repo
  IMAGE_NAME: login-app
  IMAGE_TAG: latest
  NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.GAR_ZONE }}-docker.pkg.dev

    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ env.GAR_ZONE }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.GAR_ZONE }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_REGION }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
        kubectl apply -f k8s/backendconfig.yaml
        kubectl apply -f k8s/frontendconfig.yaml
        kubectl apply -f k8s/hpa.yaml
        kubectl rollout status deployment/login-app --timeout=600s
